version: "3.7"

services:
  next:
    build:
      context: .
    image: summand-dev/summand.dev:0.1.1
    container_name: summand__summand_dev
    ports:
      - "${WEBUI_SERVER_PORT}:3000"
    restart: always
